# Generated by Django 2.1.3 on 2019-02-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190208_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, null=True, related_name='choices', to='accounts.Choice'),
        ),
    ]
